name: Nest Deploy

on:
  push:
    branches:
      - main 

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
    #idk what this is so I'll comment and see if anything breaks
    # - name: Checkout code
    #   uses: actions/checkout@v2
    #test edit to trigger the github action 
    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        # cd
        # cd ~/.ssh
        touch ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeychecking=no v205@hackclub.app

    - name: Deploy to Nest
      run: |
        ssh -o StrictHostKeychecking=no v205@hackclub.app "echo 'Hello from GitHub Actions!'"
        